---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: linuxacademy
  - name: dependency-cache

run:
  path: linuxacademy/ci/scripts/run_tests.sh
