---
resources:
  - name: linuxacademy
    type: git
    source: 
      uri: https://github.com/eyumay/linuxacademy.git
      branch: master

jobs:
  - name: Run tests
    plan:
      - get: linuxacademy
        trigger: true
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml
      - task: run the test suite 2
        file: linuxacademy/ci/tasks/run_tests.yml        
      - task: run the test suite 3
        file: linuxacademy/ci/tasks/run_tests.yml        