---
resources:
  - name: linuxacademy
    type: git
    source: 
      uri: https://github.com/eyumay/linuxacademy.git
      branch: master

jobs:
  - name: Run tests Test-1
    plan:
      - get: linuxacademy
        trigger: true
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml     
  - name: Run tests Test-2
    plan:
      - get: linuxacademy
        trigger: true
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml             
  - name: Run tests Test-3
    plan:
      - get: linuxacademy
        trigger: true
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml  
  - name: Run tests Test-4
    plan:
      - get: linuxacademy
        trigger: true
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml                  
  - name: Run tests Test-5
    plan:
      - get: linuxacademy
        trigger: true
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml          