---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: linuxacademy
    type: git
    source: &repo-source
      uri: https://github.com/eyumay/linuxacademy.git
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install dependencies
    plan:
      - get: linuxacademy
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: linuxacademy
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - task: run the test suite
        file: linuxacademy/ci/tasks/run_tests.yml